### ISSUE TITLE
Comments To Create Account Code 

### ISSUE THREAD

**Issue by Fatimatrook** [ITSE305Project/Software-Project#3]
1- Getters and Setters, replace placeholder methods get and set methods for all fields, allowing controlled access and updates.
2- Input Validation, add validation for password length and email format.
3- Avoid Printing Sensitive Information, exclude sensitive details as password from the (toString) method.

**Comment by Alwadyani** [comment]
all changed you can close the comment

**Comment by Fatimatrook** [comment]
done
